name: Window

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        shell: powershell
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -Force

      - name: Setup & Run ngrok (TCP 3389)
        shell: powershell
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
          Start-Job -ScriptBlock { .\ngrok\ngrok.exe tcp 3389 }
          Start-Sleep -Seconds 5

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Change runneradmin password
        shell: powershell
        env:
          ADMINPASSWORD: ${{ secrets.ADMINPASSWORD }}
        run: |
          net user runneradmin $Env:ADMINPASSWORD

      - name: Get Ngrok Tunnel Info
        shell: powershell
        run: |
          $data = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
          $tcp = $data.tunnels | Where-Object { $_.proto -eq "tcp" }
          echo "=============================="
          echo "RDP ADDRESS:"
          echo $tcp.public_url
          echo "USER: runneradmin"
          echo "PASS: (ADMINPASSWORD secret)"
          echo "=============================="

      - name: Keep runner alive
        shell: powershell
        run: |
          ping -t 127.0.0.1
